### ISSUE TITLE
Access OIDC token information from Angular SPA

### ISSUE THREAD

**Issue by godfriedmeesters** [sjohnr/springone-2021#10]
What would be the best way to access the information encoded in the OpenID token from the Angular SPA side? For example, I want to display the user's name in the SPA after login. 

As far as I understand no tokens at all are available directly to the SPA.

**Comment by marcusdacoregio** [comment]
You can have an endpoint in your BFF that just returns whatever is in the currently `Authentication` object, something like this:

```java
@GetMapping("/user/me")
public Authentication getCurrentAuthentication(Authentication authentication) {
    return authentication;
}
```

**Comment by godfriedmeesters** [comment]
Unfortunately I am in this specific case:

- Only an opaque access token is returned and forwarded by the gateway to the API as bearer
- When I want to know the user details (such as e-mail address) from the API, unfortunately the "user info" endpoint is our authorization server is disabled
- From the API, I can call the introspection endpoint with the forwarded opaque access token as parameter, however only very basic user info such as username is returned
- Therefore, ideally, I want all the info in the openid token, but the openid token is only available in flights-web
- So, how can I access the openid token from inside the API?

**Comment by godfriedmeesters** [comment]
Anyway I just moved
