### ISSUE TITLE
What should I do if I deploy the static resources of the SPA in nginx?

### ISSUE THREAD

**Issue by lylJson** [sjohnr/springone-2021#6]
Now the spa is served as static content from the /static directory of flights-web. 
I mean deploy the '/static directory' to nginx, because usually the static resources are developed by another group of people who are now deploying their SPA pages directly on nginx.

**Comment by sjohnr** [comment]
Hi @lylJson. I believe the only difference would be you need to configure CORS on the bff (web) application. The allowed origin in your CORS configuration would point to the domain where your UI is hosted.
