### ISSUE TITLE
If I release the page and static resources, I get the following error

### ISSUE THREAD

**Issue by lylJson** [sjohnr/springone-2021#7]
I changed the configuration of flights-web a bit like this:

```
@Bean
    SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
        // @formatter:off
        http
                .authorizeExchange(authorizeExchangeSpec -> authorizeExchangeSpec
                        .pathMatchers("/app/**", "/*.*.js", "/*.*.css", "/assets/**")
                        .permitAll())
                .authorizeExchange((authorize) -> authorize
                        .anyExchange().authenticated()
                )
                .oauth2Login(Customizer.withDefaults())
                .csrf((csrf) -> csrf
                        .csrfTokenRepository(CookieServerCsrfTokenRepository.withHttpOnlyFalse())
                );
        // @formatter:on
        return http.build();
    }
```

Then I got the following result:
![捕获2](https://user-images.githubusercontent.com/34184776/155254429-ccbdf824-cd4d-463b-8a87-373114da0789.PNG)
Maybe when the page wants to use ajax to call the interface, it gets a 302, but ajax can't handle 302 efficiently

**Comment by marcusdacoregio** [comment]
Hi @lylJson, it seems that your problem is a CORS error actually, can you double-check that? Also, if you provide a reproducible sample it'd be easier to simulate here and confirm the issue.

**Comment by lylJson** [comment]
@[marcusdacoregio](https://github.com/marcusdacoregio) thanks for the reply.
Here is my modified project：[https://github.com/lylJson/springone-2021.git](url)
Start the project and visit http://127.0.0.1:8000/app/flights
Sometimes we need to release some static pages without authentication, such as the home page, so I modified com.example.web.SecurityConfiguration

**Comment by sjohnr** [comment]
Hi @lylJson, it looks as though you have included a second `authorizeExchange` block. This is incorrect, and you would want to include the rules of both blocks in the same block.

```java
    @Bean
    SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
        // @formatter:off
        http
                .authorizeExchange((authorize) -> authorize
                        .pathMatchers("/app/**", "/*.*.js", "/*.*.css", "/assets/**").permitAll())
                        .anyExchange().authenticated()
                )
                .oauth2Login(Customizer.withDefaults())
                .csrf((csrf) -> csrf
                        .csrfTokenRepository(CookieServerCsrfTokenRepository.withHttpOnlyFalse())
                );
        // @formatter:on
        return http.build();
    }
```
